### ISSUE TITLE
Get error when try to get tollbooth_chi

### ISSUE THREAD

**Issue by BrightRan** [didip/tollbooth_chi#6]
When using the following command to try to get **`tollbooth_chi`**,
```go
go get -u "github.com/didip/tollbooth_chi"
```
it always returns the "**cannot find package**" error like as this:
```go
cannot find package "github.com/didip/tollbooth/v6" in any of:
	/opt/hostedtoolcache/go/1.15.0/x64/src/github.com/didip/tollbooth/v6 (from $GOROOT)
	/home/runner/go/src/github.com/didip/tollbooth/v6 (from $GOPATH)
cannot find package "github.com/didip/tollbooth/v6/limiter" in any of:
	/opt/hostedtoolcache/go/1.15.0/x64/src/github.com/didip/tollbooth/v6/limiter (from $GOROOT)
	/home/runner/go/src/github.com/didip/tollbooth/v6/limiter (from $GOPATH)
```
I tested on my local environment and in a GitHub Actions workflow, both get the same error.
* On my local environment (**Go v1.15.0** installed).
![error](https://user-images.githubusercontent.com/46307996/91517822-5657ab00-e921-11ea-827c-24ba699586f0.PNG)

* In the GitHub Actions workflow (see [here](https://github.com/TestWorkflowsRML/TestGo/runs/1039696413?check_suite_focus=true)).
```yaml
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2.1.2
        with:
          go-version: 1.15.0

      - name: Install dependencies
        shell: bash
        run: go get -u "github.com/didip/tollbooth_chi"
```
